"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = [ 'GDCS.py' ]
DATA_FILES = [ "Images", "Data", "UI" ]
OPTIONS = { 'iconfile': 'Images/GDAS_Logo.icns', 'includes': [ 'cffi', 'cryptography' ] }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={ 'py2app': OPTIONS },
    setup_requires=[ 'py2app' ],
    )
